/**
 * Excel processing configuration (RF01, RF02).
 * Column order in the file may differ; mapping matches headers case-insensitively.
 */

const excelConfig = {
  HEADER_ROW: 0,
  EXPECTED_COLUMNS: [
    'SUBREGIÓN',
    'MUNICIPIO',
    'PARENTESCO',
    'NOMBRE 1',
    'NOMBRE 2',
    'APELLIDO 1',
    'APELLIDO 2',
    'NOMBRE COMPLETO',
    'TIPO DE DOCUMENTO',
    'DOCUMENTO DE IDENTIDAD',
    'FECHA DE NACIMIENTO',
    'EDAD',
    'GENERO',
    'NUMERO DE CONTACTO',
    'CORREO ELECTRONICO',
    'INGRESOS FAMILIARES',
    'ENFOQUE DIFERENCIAL',
    'ZONA INTERVENCION',
    'DIRECCION O PUNTO DE REFERENCIA',
    'TIPOLOGIA DE INTERVENCIÓN',
    'SUBSIDIOS OTORGADOS EXTERNOS (fecha entidad otorgante valor)',
    'SUBSIDIOS OTORGADOS VIVA (fecha entidad otorgante valor)',
    'MINISTERIO DE VIVIENDA CIUDAD Y TERRITORIO: MATRICULA CATASTRAL',
    'VIABILIDAD',
    'VALOR DE MEJORAMIENTO',
    'DOCUMENTO POSTULADO',
    'DOCUMENTOS GRUPO FAMILIAR',
    'TTO DE DATOS',
    'SOPORTE TENENCIA',
    'SERVICIOS PÚBLICOS',
    'ZONA DE RIESGO',
    'FICHA SISBEN',
    'FCSDT',
    'REGISTRO FOTOGRÁFICO',
    'OBSERVACIONES CRUCE VUR',
    'OBSERVACIONES',
    'VIABILIDAD ETAPA 1',
    '#',
    'DIRECCIÓN DE POZUELO',
    'TIPO DE GAS',
    'PRESUPUESTO',
    'PERITAJE (SI AFECTA ESTRUCTURAL)',
    'LICENCIA (SI APLICA)'
  ],
  COLUMN_MAPPING: {
    SUBREGIÓN: 'subregion',
    MUNICIPIO: 'municipio',
    PARENTESCO: 'parentesco',
    'NOMBRE 1': 'primerNombre',
    'NOMBRE 2': 'segundoNombre',
    'APELLIDO 1': 'primerApellido',
    'APELLIDO 2': 'segundoApellido',
    'NOMBRE COMPLETO': 'nombreCompleto',
    'TIPO DE DOCUMENTO': 'tipoDocumento',
    'DOCUMENTO DE IDENTIDAD': 'numeroDocumento',
    'FECHA DE NACIMIENTO': 'fechaNacimiento',
    EDAD: 'edad',
    GENERO: 'genero',
    'NUMERO DE CONTACTO': 'telefono',
    'CORREO ELECTRONICO': 'email',
    'INGRESOS FAMILIARES': 'ingresosFamiliares',
    'ENFOQUE DIFERENCIAL': 'enfoqueDiferencial',
    'ZONA INTERVENCION': 'zonaIntervencion',
    'DIRECCION O PUNTO DE REFERENCIA': 'direccion',
    'TIPOLOGIA DE INTERVENCIÓN': 'tipologiaIntervencion',
    'SUBSIDIOS OTORGADOS EXTERNOS (fecha entidad otorgante valor)': 'subsidiosExternos',
    'SUBSIDIOS OTORGADOS VIVA (fecha entidad otorgante valor)': 'subsidiosViva',
    'MINISTERIO DE VIVIENDA CIUDAD Y TERRITORIO: MATRICULA CATASTRAL': 'matriculaCatastral',
    VIABILIDAD: 'viabilidad',
    'VALOR DE MEJORAMIENTO': 'valorMejoramiento',
    'DOCUMENTO POSTULADO': 'documentoPostulado',
    'DOCUMENTOS GRUPO FAMILIAR': 'documentosGrupoFamiliar',
    'TTO DE DATOS': 'tratamientoDatos',
    'SOPORTE TENENCIA': 'soporteTenencia',
    'SERVICIOS PÚBLICOS': 'serviciosPublicos',
    'ZONA DE RIESGO': 'zonaRiesgo',
    'FICHA SISBEN': 'fichaSisben',
    FCSDT: 'fcsdt',
    'REGISTRO FOTOGRÁFICO': 'registroFotografico',
    'OBSERVACIONES CRUCE VUR': 'observacionesCruceVUR',
    OBSERVACIONES: 'observaciones',
    'VIABILIDAD ETAPA 1': 'viabilidadEtapa1',
    '#': 'numeroFila',
    'DIRECCIÓN DE POZUELO': 'direccionPozuelo',
    'TIPO DE GAS': 'tipoGas',
    PRESUPUESTO: 'presupuesto',
    'PERITAJE (SI AFECTA ESTRUCTURAL)': 'peritaje',
    'LICENCIA (SI APLICA)': 'licencia'
  },
  BATCH_SIZE: 1000,
  DYNAMIC_BATCH_SIZING: true,
  BATCH_SIZE_THRESHOLDS: {
    small: { maxRows: 10000, batchSize: 1000 },
    medium: { maxRows: 50000, batchSize: 500 },
    large: { maxRows: Infinity, batchSize: 250 }
  },
  COUNT_ROWS: true,
  VALIDATIONS: {
    required: ['MUNICIPIO', 'NOMBRE COMPLETO', 'TIPO DE DOCUMENTO', 'DOCUMENTO DE IDENTIDAD'],
    uniqueFields: ['DOCUMENTO DE IDENTIDAD'],
    emailFields: ['CORREO ELECTRONICO'],
    dateFields: ['FECHA DE NACIMIENTO'],
    numericFields: ['EDAD', 'INGRESOS FAMILIARES', 'VALOR DE MEJORAMIENTO']
  },
  LOG_LEVEL: 'info',
  LOG_TO_FILE: true,
  LOG_FILE_PATH: './logs/excel-processing.log',
  MEMORY_MANAGEMENT: {
    forceGC: true,
    memoryCheckInterval: 100
  }
};

module.exports = excelConfig;
